name: MPPT 1210 HUS
version: 0.1
function: connecting OSH modules
function-category: knowledge base
license: https://github.com/LibreSolar/mppt-1210-hus/blob/master/LICENSE
readme: https://github.com/LibreSolar/mppt-1210-hus/blob/master/README.md
certificate:
contributing:
standard: 
functional-metadata:
  - 12V battery voltage
  - 40V max. solar input (36 to 48-cell panels, ideally so-called 12V panels with 36 cells)
  - 10A max. charge current
  - 10A max. load output current
  - Low-power 32bit ARM MCU (STM32L072)
  - Expandable via Olimex Universal Extension Connector (UEXT) featuring I2C, Serial and SPI interface (e.g. used for display, WIFI communication, etc.)
  - USB charging
  - High-side load switching
  - Overvoltage protection
  - Undervoltage protection
  - Overcurrent protection
  - PV short circuit protection
  - PV reverse polarity protection
  - Battery reverse polarity (destructive, fuse is blown) protection 
TsDC: TsDC-ASM-PCB
source-3d
source-2d
source+
export-3d
export-2d
export+
consists-of:
  part-1,1,link
  part-2,3,link
  asm-1,1,link
    part-3,2,link
    screws,4,M8x20