name: MPPT 1210 HUS
organisation: LibreSolar
version: v0.7.1
language: EN
function: This charge controller is a so-called maximum power point tracker (MPPT), which automatically adapts its input voltage to the connected solar panel to extracts as much power as possible. The MPPT function can only be achieved using a DC/DC converter, which is the core part of the charge controller PCB. It can be recognized by the large inductor and the large electrolytic input and output filter capacitors.
function-category: maximum power point tracking
license: https://github.com/LibreSolar/mppt-1210-hus/blob/master/LICENSE
readme: https://github.com/LibreSolar/mppt-1210-hus/blob/master/README.md
certificate:
contributing:
standard:
functional-metadata:
  12V battery voltage
  40V max. solar input (36 to 48-cell panels, ideally so-called 12V panels with 36 cells)
  10A max. charge current
  10A max. load output current
  Low-power 32bit ARM MCU (STM32L072)
  Expandable via Olimex Universal Extension Connector (UEXT) featuring I2C, Serial and SPI interface (e.g. used for display, WIFI communication, etc.)
  USB charging
  High-side load switching
  Overvoltage protection
  Undervoltage protection
  Overcurrent protection
  PV short circuit protection
  PV reverse polarity protection
  Battery reverse polarity protection (destructive, fuse is blown) 
TsDC: TsDC-ASM-PCB
source-3d:
source-2d: https://github.com/LibreSolar/mppt-1210-hus/blob/master/kicad/mppt-1210-hus.kicad_pcb
source+:
  https://github.com/LibreSolar/mppt-1210-hus/tree/master/manual
export-3d:
export-2d: https://github.com/LibreSolar/mppt-1210-hus/blob/master/mppt-1210-hus.pdf
export+:
  https://libre.solar/mppt-1210-hus/
  https://libre.solar/mppt-1210-hus/manual.pdf
consists-of:
  C2	150u	CP_Elec_8x6.2	1
  C5	820u	CP_Radial_D10.0mm_P5.00mm	1
  C1	1200u	CP_Radial_L31.5mm_D16.0mm_P7.50mm_horizontal	1
  C9, C10, C19, C24, C25, C26, C30, C31, C32, C39, C42, C43	100n	C_0603_1608	12
  C4, C7, C8, C17, C18, C27, C28, C37, C41, C44	10n	C_0603_1608	10
  C12, C23, C33, C34, C38	2.2u	C_0603_1608	5
  C6, C11, C13	1n	C_0603_1608	3
  C29	220n	C_0603_1608	1
  C35	100p	C_0603_1608	1
  C14	1u	C_0805_2012	1
  C20, C21, C36, C40	22u	C_1206_3216	4
  C3	4.7u	C_1210_3225	1
  C15	10u	C_1210_3225	1
  R12, R22, R23, R24, R25, R28, R35, R36	100k	R_0603_1608	8
  R5, R7, R13, R30, R33, R34	2.2k	R_0603_1608	6
  R11, R14, R15, R18, R20, R21	470	R_0603_1608	6
  R9, R16, R19, R31	10k	R_0603_1608	4
  R26, R27	5.6k	R_0603_1608	2
  R29, R32	24.9k	R_0603_1608	2
  R2	1M	R_0603_1608	1
  R8	100	R_0603_1608	1
  R1, R3, R10	4.7	R_0805_2012	3
  R4	2.2	R_1206_3216	1
  R6, R17	3m	R_Bourns_CRE2512	2
  L3	10uH	Bourns_SRN8040TA	1
  L1	47uH	L-FERYSTER-DTMSS-27_47uH	1
  L2	2.2uH	L_1210_3225Metric	1
  D5	SMBJ24A	D_SMB	1
  D1, D4, D7	1N4148	D_SOD-123	3
  D6	SS14FL	D_SOD-123	1
  U2	STM32L072CZT6	LQFP-48_7x7mm_P0.5mm	1
  U1	LM5109BMA	SOIC-8_3.9x4.9mm_Pitch1.27mm	1
  U5	AP2210-3.3	SOT-23-5	1
  U3, U4	D1213A-04SO	SOT-23-6	2
  U9	LMR33630	TI_SO-PowerPAD-8_ThermalVias	1
  U6	INA2181	VSSOP-10_3.0x3.0mm_P0.5mm	1
  F1	25A	KEYSTONE-FUSE-3557-2	1
  F2	50mA	R_1206_3216	1
  Q1, Q2, Q4	PSMN5R2-60YLX	5X6_MOSFET	3
  Q3	BSC084P03NS3	5X6_MOSFET	1
  LED1, LED2, LED3	yellow	LED_0603_D3.0mm	3
  LED4, LED5	green	LED_0603_D3.0mm	2
  LOGO1	LIBRE_SOLAR	LIBRESOLAR_LOGO	1
  RT1	10k NTC	R_0603_1608	1
  Q5, Q6, Q7	BSS83P	SOT-23	3
  T1, T2	MMBT3904	SOT-23	2
  J4	UEXT	Box_Header_2x05x2.54mm_Straight	1
  J6	PWR_12V	JST_XH_B02B-XH-A_1x02_P2.50mm_Vertical	1
  J1, J2, J3	MKDS_5-2_952	Phoenix_Contact_MKDS_5-2-952	3
  J8	ST_Nucleo_SWD	PinHeader_1x05_P2.54mm_Vertical	1
  J7	6P6C	RJ25_6P6C_TabUp	1
  J5	USB_A_stacked	USB_A_Wuerth_61400826021_Horizontal_Stacked	1
