[OHLOOM]
okhv = "2.0"
repo = "https://gitlab.com/OSEGermany/ohloom"
version = "1.0.0"
spdx-license = "CC-BY-SA-4.0"
licensor = "Jens Meisner"
readme = "README.md"
image = "/Documentation/User_Guide/User_Guide.jpg"
documentation-language = "en-GB"
open-technology-readiness-level = "OTLR-5"
function = "The Open Hardware Loom is a simple, hand-operated weaving loom made of wood, screws and 3D printed plastic pieces for the most part. It is simple to make and operate."
cpc-patent-class = "D03D 35/00"
tsdc-id = "ASM-MEC"
bom = "sBoM.csv"
assembly-instruction = "/Documentation/Assembly_Guide/AssemblyGuide.md"

[OHLOOM.functional-metadata]
fabric-width-dim = "mm"
fabric-width = 400

[OHLOOM.production-metadata]
outer-dimension-dim = "mm"
outer-dimension = "cube(size = [400,350,150]"

[ClampRing]
image = "/Documentation/Assembly_Guide/Parts_Print_2.jpg"
tsdc-id = "COM-MAN"
source = "/3DParts/ClampRing/ClampRing.scad"
export = [
  "/3DParts/ClampRing/ClampRing.pdf",
  "/3DParts/ClampRing/ClampRing.stl"
]

[ClampRing.production-metadata]

process = "3D printed"
material = "PLA"
outer-dimension-dim = "mm"
outer-dimension = "cylinder(h=30, r=28)"

[CombModul]
image = "Documentation/Assembly_Guide/Parts_Print_3.jpg"
tsdc-id = "COM-MAN"
source = "/3DParts/CombModul/CombModul.scad"
export = [
  "/3DParts/CombModul/CombModul.pdf",
  "/3DParts/CombModul/CombModul.stl"
]

[CombModul.production-metadata]

process = "3D printed"
material = "PLA"
outer-dimension-dim = "mm"
outer-dimension = "cube(size = [120,100,3]"

[PoleBase]
tsdc-id = "COM-MAN"
source = "/3DParts/PoleBase/PoleBase.scad"
export = "/3DParts/PoleBase/PoleBase.stl"

[PoleBase.production-metadata]

process = "3D printed"
material = "PLA"
outer-dimension-dim = "mm"
outer-dimension = "cube(size = [125,110,100]"

[RatchetPawl]
image = "Documentation/Assembly_Guide/Parts_Print_4.jpg"
tsdc-id = "COM-MAN"
source = "/3DParts/RatchetPawl/RatchetPawl.scad"
export = [
  "/3DParts/RatchetPawl/RatchetPawl.pdf",
  "/3DParts/RatchetPawl/RatchetPawl.stl"
]

[RatchetPawl.production-metadata]

process = "3D printed"
material = "PLA"
outer-dimension-dim = "mm"
outer-dimension = "cube(size = [130,20,20]"

[RatchetWheel]
image = "Documentation/Assembly_Guide/Parts_Print_1.jpg"
tsdc-id = "COM-MAN"
source = "/3DParts/RatchetWheel/RatchetWheel.scad"
export = [
  "/3DParts/RatchetWheel/RatchetWheel.pdf",
  "/3DParts/RatchetWheel/RatchetWheel.stl"
]

[RatchetWheel.production-metadata]

process = "3D printed"
material = "PLA"
outer-dimension-dim = "mm"
outer-dimension = "cylinder(h=45, r=45)"

[ScrewSockets]
image = "/Documentation/Assembly_Guide/Parts_Print_6.jpg"
tsdc-id = "COM-MAN"
source = "/3DParts/ScrewSockets/ScrewSockets.scad"
export = [
  "/3DParts/ScrewSockets/ScrewSockets.pdf",
  "/3DParts/ScrewSockets/ScrewSockets.stl"
]

[ScrewSockets.production-metadata]

process = "3D printed"
material = "PLA"
outer-dimension-dim = "mm"
outer-dimension = "cylinder(h=12, r=7)"

[ScrewSockets4ScrewHead]
image = "/Documentation/Assembly_Guide/Parts_Print_5.jpg"
tsdc-id = "COM-MAN"
source = "/3DParts/ScrewSockets/ScrewSockets.scad"
export = "/3DParts/ScrewSockets/ScrewSocket4ScrewHead.stl"

[ScrewSockets4ScrewHead.production-metadata]

process = "3D printed"
material = "PLA"
outer-dimension-dim = "mm"
outer-dimension = "cylinder(h=12, r=7)"

[Warpclothbeam_1]
image = "Documentation/Assembly_Guide/Parts_Print_7.jpg"
tsdc-id = "COM-MAN"
source = "/3DParts/WarpClothBeam/Warpclothbeam_P1.scad"
export = [
  "/3DParts/WarpClothBeam/Warpclothbeam_P1.pdf",
  "/3DParts/WarpClothBeam/Warpclothbeam_1.stl"
]

[Warpclothbeam_1.production-metadata]

process = "3D printed"
material = "PLA"
outer-dimension-dim = "mm"
outer-dimension = "cylinder(h=162, r=22.5)"

[Warpclothbeam_2]
image = "Documentation/Assembly_Guide/Parts_Print_7.jpg"
tsdc-id = "COM-MAN"
source = "/3DParts/WarpClothBeam/Warpclothbeam_P2.scad"
export = [
  "/3DParts/WarpClothBeam/Warpclothbeam_P2.pdf",
  "/3DParts/WarpClothBeam/Warpclothbeam_2.stl"
]

[Warpclothbeam_2.production-metadata]

process = "3D printed"
material = "PLA"
outer-dimension-dim = "mm"
outer-dimension = "cylinder(h=163, r=22.5)"

[Warpclothbeam_3]
image = "Documentation/Assembly_Guide/Parts_Print_7.jpg"
tsdc-id = "COM-MAN"
source = "/3DParts/WarpClothBeam/Warpclothbeam_P3.scad"
export = [
  "/3DParts/WarpClothBeam/Warpclothbeam_P3.pdf",
  "/3DParts/WarpClothBeam/Warpclothbeam_3.stl"
]

[Warpclothbeam_3.production-metadata]

process = "3D printed"
material = "PLA"
outer-dimension-dim = "mm"
outer-dimension = "cylinder(h=163, r=22.5)"

[Warpclothbeam_4]
image = "Documentation/Assembly_Guide/Parts_Print_7.jpg"
tsdc-id = "COM-MAN"
source = "/3DParts/WarpClothBeam/Warpclothbeam_P4.scad"
export = [
  "/3DParts/WarpClothBeam/Warpclothbeam_P4.pdf",
  "/3DParts/WarpClothBeam/Warpclothbeam_4.stl"
]

[Warpclothbeam_4.production-metadata]

process = "3D printed"
material = "PLA"
outer-dimension-dim = "mm"
outer-dimension = "cylinder(h=162, r=22.5)"

[CombHolder]
image = "/Documentation/Assembly_Guide/Parts_CNC_1.jpg"
tsdc-id = "COM-MAN"
source = "/WoodParts/CombHolder/CombHolder.scad"
export = [
  "/WoodParts/CombHolder/CombHolder.pdf",
  "/WoodParts/CombHolder/CombHolder.stl"
]

[CombHolder.production-metadata]

process = "machined"
material = "wood"
outer-dimension-dim = "mm"
outer-dimension = "cube(size = [118,60,18]"

[CrossBeam]
image = "/Documentation/Assembly_Guide/Parts_CNC_3.jpg"
tsdc-id = "COM-MAN"
source = "/WoodParts/CrossBeam/CrossBeam.scad"
export = [
  "/WoodParts/CrossBeam/CrossBeam.pdf",
  "/WoodParts/CrossBeam/CrossBeam.stl"
]

[CrossBeam.production-metadata]

process = "machined"
material = "wood"
outer-dimension-dim = "mm"
outer-dimension = "cube(size = [572,100,20]"

[Shuttle]
image = "/Documentation/Assembly_Guide/Parts_CNC_6.jpg"
tsdc-id = "COM-MAN"
source = "/WoodParts/Shuttle/Shuttle.scad"
export = [
  "/WoodParts/Shuttle/Shuttle.pdf",
  "/WoodParts/Shuttle/Shuttle.stl"
]

[Shuttle.production-metadata]

process = "machined"
material = "wood"
outer-dimension-dim = "mm"
outer-dimension = "cube(size = [497,45,6]"

[SideFrame]
image = "/Documentation/Assembly_Guide/Parts_CNC_2.jpg"
tsdc-id = "COM-MAN"
source = "/WoodParts/SideFrame/SideFrame.scad"
export = [
  "/WoodParts/SideFrame/SideFrame.pdf",
  "/WoodParts/SideFrame/SideFrame.stl"
]

[SideFrame.production-metadata]

process = "machined"
material = "wood"
outer-dimension-dim = "mm"
outer-dimension = "cube(size = [580,140,18]"

[SlotBeam]
image = "/Documentation/Assembly_Guide/Parts_CNC_4.jpg"
tsdc-id = "COM-MAN"
source = "/WoodParts/SlotBeam/SlotBeam.scad"
export = [
  "/WoodParts/SlotBeam/SlotBeam.pdf",
  "/WoodParts/SlotBeam/SlotBeam.stl"
]

[SlotBeam.production-metadata]

process = "machined"
material = "wood"
outer-dimension-dim = "mm"
outer-dimension = "cube(size = [566,24,22]"

[StringStick]
image = "/Documentation/Assembly_Guide/Parts_CNC_5.jpg"
tsdc-id = "COM-MAN"
source = "/WoodParts/StringStick/StringStick.scad"
export = [
  "/WoodParts/StringStick/StringStick.pdf",
  "/WoodParts/StringStick/StringStick.stl"
]

[StringStick.production-metadata]

process = "machined"
material = "wood"
outer-dimension-dim = "mm"
outer-dimension = "cube(size = [560,22,6]"

[WarpClothBeam]
image = "/Documentation/Assembly_Guide/Parts_Other_1.jpg"
tsdc-id = "COM-MAN"
source = "/WoodParts/WarpClothBeam_NoCNC/WarpClothBeam_Wood_NoCNC.scad"
export = [
  "/WoodParts/WarpClothBeam_NoCNC/WarpClothBeam_Shaft.pdf",
  "/WoodParts/WarpClothBeam_NoCNC/WarpClothBeam_Wood_NoCNC.stl"
]

[WarpClothBeam.production-metadata]

process = "machined"
material = "wood"
outer-dimension-dim = "mm"
outer-dimension = "cylinder(h=710, r=17.5)"
