[your-awesome-OSH]
okhv = "2.0"
repo = "https://gitlab.com/xxx"
version = "1.0.0"
spdx-license = "CERN-OHL-S-2.0"
licensor = "xxx"
readme = "README.md"
image = "xxx.jpg"
documentation-language = "en-GB"
open-technology-readiness-level = "OTLR-5"
function = "xxx"
cpc-patent-class = "get CPC-ID from here <https://worldwide.espacenet.com/classification> e.g. D03D 35/00"
tsdc-id = "ASM-MEC"
bom = "BoM.csv"
assembly-instruction = "/Documentation/Assembly_Guide/AssemblyGuide.md"

[your-awesome-OSH.functional-metadata]
fabric-width-mm = 400

[your-awesome-OSH.production-metadata]
outer-dimension-dim = "mm"
outer-dimension = "cube(size = [400,350,150]"

[your-awesome-part1]
image = "xxx.jpg"
tsdc-id = "COM-MAN"
source = "xxx.scad"
export = [
  "xxx.pdf",
  "xxx.stl"
]

[your-awesome-part1.production-metadata]

process = "3D printed"
material = "PLA"
outer-dimension-dim = "mm"
outer-dimension = "cube(size = [120,100,3]"
